### ISSUE TITLE
can not move down in visual mode when have blank line

### ISSUE THREAD

**Issue by ghking1** [NeoVintageous/NeoVintageous#376] opened 2018-09-15 16:45 UTC
![image](https://user-images.githubusercontent.com/8264304/45588599-c1349500-b949-11e8-866d-41717128ebdf.png)

**Comment by gerardroche** [comment] 2018-09-23 20:58
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/18

**Closed by gerardroche** 2018-09-23 20:58 UTC
