### ISSUE TITLE
Sorting Lines

### ISSUE THREAD

**Issue by GaryFurash** [NeoVintageous/NeoVintageous#300] opened 2018-01-15 16:22 UTC
### Steps to Reproduce
1. Visually select (or select with cursor) multiple lines
2. :sort 
nothing happens
3. Ctrl-Shift-P Sort
sorts entire file

Turning off NeoVintageous makes Ctrl-Shift-P work as normal (sorts selected lines)

### Expected behaviour
:sort - sorts selected lines
Ctrl-Shift-P Sort - sorts selected lines

### Actual behaviour
:sort - nothing
Ctrl-Shift-P Sort - sorts entire file

### Versions

You can get Sublime Text version information from copy and pasting the output of the console `Menu > View > Show Console`.

Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

You can get debugging information by copy and pasting the output of the console `Menu > View > Show Console`.

Command and input logging can be enabled from the console (run the commands in input box at the bottom of the console): `sublime.log_commands(True)` for command logging, and `sublime.log_input(True)` input logging. See the [debugging guide](https://github.com/NeoVintageous/NeoVintageous/CONTRIBUTING.md#debugging) for more detailed debugging information.

**Comment by gerardroche** [comment] 2018-01-17 12:37
Sort commands e.g. `:sort u` are not supported. In the meantime you can setup a mapping to use ST's sorting command via `F9`:

Edit your `vintageousrc` file (from the command palette: `NeoVintageous: Open My .vintageousrc File`), and add:

```
let mapleader=,

vnoremap <leader>s <F9>o<Esc>
```

Now you can select text and then sort with the command `,s`. See `:h neovintageous` for more details on the `vintageousrc` file.

# Explaination of the Mapping

* `F9` sorts the selected text using ST's `F9` sort command  
* `o` moves the cursor after the sort to the beginning of the selection
* `<Esc>` puts us back in normal mode

You can get fancy about it too (I use this all the time), sorting a paragraph directly from normal mode:

```
nnoremap <leader>s vip<F9>o<Esc>
```

* `vip` visually selects the inner paragraph.

**Comment by gerardroche** [comment] 2018-02-26 00:36
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/273

**Closed by gerardroche** 2018-02-26 00:36 UTC
Labels: duplicate
