### ISSUE TITLE
Support Ctrl-6 

### ISSUE THREAD

**Issue by sdemura** [NeoVintageous/NeoVintageous#736] opened 2020-06-01 19:33 UTC
```
							*CTRL-^* *CTRL-6*
CTRL-^			Edit the alternate file.  Mostly the alternate file is
			the previously edited file.  This is a quick way to
			toggle between two files.  It is equivalent to ":e #",
			except that it also works when there is no file name.

```

This is an vital part of my vim workflow. Would like to see this used here!

**Comment by gerardroche** [comment] 2020-06-05 10:04
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/74

**Closed by gerardroche** 2020-06-05 10:04 UTC
Labels: duplicate
