### ISSUE TITLE
Duplicate register status when " is mapped to a key

### ISSUE THREAD

**Issue by eugenesvk** [NeoVintageous/NeoVintageous#1003] opened 2024-02-10 14:49 UTC
`nnoremap a "`  then pressing `a` results in `""` duplicate status instead of a single `"` since the first `"` is not cleaned up for some reason 

In fact, maybe the bigger problem is that the registers are broken:
If I map a line delete to Shift+X `nnoremap X dd`, then `"zX` doesn't fill the `z` register, while the `"zdd` does, seems due to process notating cleaning up the registers (`reset_command_data`) if action exists, but not sure what the proper fix for that is

**Comment by gerardroche** [comment] 2024-02-11 11:36
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/931 ?

**Comment by eugenesvk** [comment] 2024-02-11 11:53
The first one is indeed a duplicate, though it's not just about single quotes, seems like any remap behaves the same

Though the second one with the registers is different?

I'm using a workaround [here](https://github.com/eugenesvk/NeoVintageous/commit/3c90741dd37a7928fdab1ee652b159352bca7dc4) that doesn't reset register if it's not the default `"` when an action is primed in a sequence, but not sure whether that brings some other issues since that double iteration logic is a bit convoluted

**Closed** 2024-02-11 12:15 UTC
Labels: bug
