### ISSUE TITLE
Unable to map <leader>0 or other digits

### ISSUE THREAD

**Issue by kkekk** [NeoVintageous/NeoVintageous#434] opened 2019-02-11 04:13 UTC
### Description
in `.vintageousrc`
1) `nnoremap <leader>f :ToggleSideBar<CR>`
2) `nnoremap <leader>0 :ToggleSideBar<CR>`
3) `nnoremap <leader>1 :ToggleSideBar<CR>`
First mapping works, but second mapping and the third does not work. I had tested it with other commands (:FocusSideBar) as well.

### Versions
Sublime text version 3176

Ubuntu 18.04.1 LTS

**Comment by gerardroche** [comment] 2019-02-11 06:44
This is related to the case-insensitive keys issue: https://github.com/NeoVintageous/NeoVintageous/issues/433. The issue is that numbers and double quotes can't be mapped. This due to the way the mappings are parsed internally: leading quotes and numbers are stripped before resolving the mappings.

**Comment by gerardroche** [comment] 2019-02-11 06:45
fyi there's a built in toggle sidebar command provided that integrates better with neo. See `:h nv` for more details and here:

```

A command is providied out-of-the-box for mapping to toggle the side bar:

    nnoremap <leader>d :NeovintageousToggleSideBar<CR>

To enable the ability to toggle the side bar when the side bar has focus:

`Menu > Preferences > Key Bindings`: >

    [
        {
            "keys": [",", "d"],
            "command": "neovintageous_toggle_side_bar",
            "context": [
                { "key": "control", "operand": "sidebar_tree" }
            ]
        }
    ]
```

**Closed** 2019-03-24 05:30 UTC
Labels: bug, enhancement, mappings
