### ISSUE TITLE
Implement g_ g0 g^ g$

### ISSUE THREAD

**Issue by jnns** [NeoVintageous/NeoVintageous#810] opened 2022-02-22 10:40 UTC
It would be very helpful if these commands were available. Especially when editing very long visually wrapped lines. 

Thanks for considering and your ongoing efforts with this awesome package! 🙏🏻 

> - **g0 or g<Home>**		
>   When lines wrap ('wrap' on): To the first character of
> 			the screen line.  |exclusive| motion.  Differs from
> 			"0" when a line is wider than the screen.
> 			When lines don't wrap ('wrap' off): To the leftmost
> 			character of the current line that is on the screen.
> 			Differs from "0" when the first character of the line
> 			is not on the screen.
> 
> - **g^**		
>   When lines wrap ('wrap' on): To the first non-blank
> 			character of the screen line.  |exclusive| motion.
> 			Differs from "^" when a line is wider than the screen.
> 			When lines don't wrap ('wrap' off): To the leftmost
> 			non-blank character of the current line that is on the
> 			screen.  Differs from "^" when the first non-blank
> 			character of the line is not on the screen.
> 
> - **g$ or g<End>**		
>    When lines wrap ('wrap' on): To the last character of
> 			the screen line and [count - 1] screen lines downward
> 			|inclusive|.  Differs from "$" when a line is wider
> 			than the screen.
> 			When lines don't wrap ('wrap' off): To the rightmost
> 			character of the current line that is visible on the
> 			screen.  Differs from "$" when the last character of
> 			the line is not on the screen or when a count is used.
> 			Additionally, vertical movements keep the column,
> 			instead of going to the end of the line.
> 			When 'virtualedit' is enabled moves to the end of the
> 			screen line.

**Comment by nk9** [comment] 2022-03-20 16:27
Looks like a duplicate of #757

**Comment by gerardroche** [comment] 2023-08-09 09:20
Dup of https://github.com/NeoVintageous/NeoVintageous/issues/757

**Closed by gerardroche** 2023-08-09 09:20 UTC
Labels: feature, motion, wordwrap
