### ISSUE TITLE
Plugin doesn't handle autocomplete correctly

### ISSUE THREAD

**Issue by everdimension** [NeoVintageous/NeoVintageous#626] opened 2019-08-21 09:59 UTC
Basically I want to reopen this issue: https://github.com/NeoVintageous/NeoVintageous/issues/387

I think this should still be fixed within the plugin, because it's still a bug.
Having a userland workaround is nice, but you cannot expect everyone to search github issues to make the plugin work as expected.

Thank you.

**Comment by gerardroche** [comment] 2019-08-21 14:53
I don't seem to be able to reproduce the issue. There's possibly a conflict with another plugin, a difference in configurations, or I'm misunderstanding the issue. What I've tried:

Start with a view with the following text, where `|` is the cursor, starting in normal mode:

```
TestOne
TestTwo
TestThree

|

x

y
```

Press `i` to enter insert mode, type **Test** and select a completion with the arrow keys:

![1](https://user-images.githubusercontent.com/44148/63439017-34ca0680-c425-11e9-925a-728893fd9367.png)

From here press  <kbd>Enter</kbd> (if you have `auto_complete_commit_on_tab` set to false, otherwise you use press <kbd>Tab</kbd> to commit the completion). With the above example we complete **TestTwo**. 

Then <kbd>Esc</kbd> to go to normal mode, and then press <kbd>jjj.</kbd> to move the cursor to the line between the x and y and repeat, which repeats **TestTwo**.

![two1](https://user-images.githubusercontent.com/44148/63442865-bae94b80-c42b-11e9-9cdd-7ee768297b51.png)


Could you try disabling some plugins to see if you can get the same as the above? Or am I misunderstanding the issue?

**Comment by gerardroche** [comment] 2019-08-21 15:01
Also can you enable some logging and see what commands are being called:


Show the Sublime Text console log: **Menu > View > Show Console**.

Command and input logging are enabled by running the following commands in input box at the bottom of the console: `sublime.log_commands(True)` and `sublime.log_input(True)`.

See https://github.com/NeoVintageous/NeoVintageous/blob/master/CONTRIBUTING.md#debugging

**Comment by everdimension** [comment] 2019-08-21 21:45
![sublime-vim-gif](https://user-images.githubusercontent.com/5347023/63469046-f6a70400-c471-11e9-836d-c7b04a51d392.gif)


Console output is something like this:

```
_vi_o
chr evt: D (0x44)
chr evt: i (0x69)
key evt: enter
command: insert_dimensions
insert_dimensions
key evt: escape
command: _nv_feed_key {"key": "<esc>"}
chr evt: j (0x6a)
command: _nv_feed_key {"key": "j"}
chr evt: . (0x2e)
command: _nv_feed_key {"key": "."}
sequence
chr evt: . (0x2e)
command: _nv_feed_key {"key": "."}
sequence
```

I tried disabling "All Autocomplete" plugin, the problem persists

**Comment by gerardroche** [comment] 2019-08-21 22:56
From your log I see that when you press Enter it's triggering a command `insert_dimensions` when it should trigger `commit_completion`. Do you have [https://packagecontrol.io/packages/AutoFileName](AutoFileName) installed?

**Comment by everdimension** [comment] 2019-08-21 23:04
@gerardroche Hm, yeah, I have that plugin

Turning it off seems to have fixed the problem. Do you believe it's a bug with that plugin?

**Comment by gerardroche** [comment] 2019-08-21 23:32
The plugin has 1.2m downloads but it hasn't been modified in over 5 years with a lot of open issues. 

The issue is that the plugin overrides the on Enter key commit completions and wraps it in additional behaviours but then doesn't handle repeating the command properly.

The solution for the other users was to override the keymap defined by AutoFileName with the the original keymap. Perhaps the AutoFileName should allow users to disable the keymaps or make the insert_dimensions command compatible with the wrapped `commit_completion` command, but the plugin hasn't been updated in years so I doubt it will be fixed.

**Comment by gerardroche** [comment] 2020-01-16 18:10
The AutoFileName is too old and too broken for us to try to work its issues. I don't people realise how much AutoFileName breaks ST auto complete. For example, it completely breaks auto complete in strings. 

AutoFileName was developed long before new completions APIs were added to ST. Currently it overrides ST auto complete behaviours in a number of scopes and contexts. That's not really what it should be doing. Instead it should only *add* relevant completions in relevant scopes and contexts.

**Closed by gerardroche** 2020-01-16 18:10 UTC
