### ISSUE TITLE
*Ncgn doesn't work

### ISSUE THREAD

**Issue by nlack** [NeoVintageous/NeoVintageous#503] opened 2019-04-09 19:19 UTC
### Description
For quick iterative refactoring in vim i often use the `*Ncgn` command combination.
For a good description see: https://www.youtube.com/watch?v=7Bx_mLDBtRc

### Steps to Reproduce
Try *Ncgn in normal mode with cursor over `variable`.
```
const variable = '';

if (variable) {
 // ...
}
```
### Expected behaviour
Move the cursor over the word you want to refactor and press in normal mode `*Ncgn`.
After the `n` you should be in insert mode and with every `.` pressed after being back in normal mode, the next occurring word should change to you insert mode edit.
### Actual behaviour
After pressing the last `n`, the expected insert mode doesn't start.
### Versions
startup, version: 3206 linux x64 channel: dev
NeoVintageous in package manager list v1.11.3

### Additional Information
```
chr evt: * (0x2a)
command: _nv_feed_key {"key": "*"}
chr evt: N (0x4e)
command: _nv_feed_key {"key": "N"}
chr evt: c (0x63)
command: _nv_feed_key {"key": "c"}
chr evt: g (0x67)
command: _nv_feed_key {"key": "g"}
chr evt: n (0x6e)
command: _nv_feed_key {"key": "n"}
```

**Comment by gerardroche** [comment] 2019-04-09 21:06
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/382

**Closed by gerardroche** 2019-04-09 21:06 UTC
Labels: duplicate
