### ISSUE TITLE
Symbol jumping does not select text

### ISSUE THREAD

**Issue by slifin** [NeoVintageous/NeoVintageous#753] opened 2020-11-13 16:18 UTC
**Describe the bug**  
Prevents symbols from being selected when jumped to from symbol search

**To Reproduce**  

1. Open a file with symbols
2. Press command + r to fuzzy search symbols
3. Press enter

**Expected behavior**  
The select symbol name fully selected inside the buffer

**Actual behavior**  
The cursor is placed at the start of the symbol name in the code but the symbol name is not selected

**Versions**  
macos 4090

**Additional Information**  
This behaviour works in sublime text 4 if the neovintageous plugin is disabled

**Comment by gerardroche** [comment] 2020-12-03 14:11
This is expected behaviour for vim commands i.e. the jump does nor create a visual selection. We can maybe at some point have a setting for enabling/disabling the visual selection, but I think it would be dependent on https://github.com/sublimehq/sublime_text/issues/3032 which arose because of issues like https://github.com/NeoVintageous/NeoVintageous/issues/54

**Comment by gerardroche** [comment] 2023-05-24 21:12
Closing because it's a Sublime Text limitation and there isn't really anything I can do about it. I've added it to the known issues section on the roadmap so it won't be forgotten. https://github.com/NeoVintageous/NeoVintageous/issues/854

**Closed by gerardroche** 2023-05-24 21:12 UTC
Labels: feature, options, known-sublime-text-issue
