### ISSUE TITLE
:w not triggering formatter, but :Save and <C-s> do

### ISSUE THREAD

**Issue by lazamar** [NeoVintageous/NeoVintageous#386] opened 2018-11-20 11:50 UTC
### Description
The `:w` command is saving my Elm files but is not triggering automatic formatting. If I use <C-s> or `:Save` it saves and formats the file as expected.
`:w` does save and trigger the formatter for other file types such as JavaScript files.

### Steps to Reproduce
- Install the latest stable release of sublime
- Install SublimeLinter and the Elm language package plugins for sublime
- Install elm formatters `npm install -g elm elm-format`
- Turn on format on save in SublimeLInter
- Try to save a file with `:w` and you will see that it doesn't format, but with `:Save` and <C-s> it does. 

### Versions
I'm using Neovintageous `1.7.0` and Sublime `3176` on Ubuntu `18.04`

**Comment by gerardroche** [comment] 2018-12-23 15:16
Hmm. There is a slight difference in the way **:Save** and **:w** operate. I'll need to investigate it to see if I can resolve it.

**Comment by gerardroche** [comment] 2019-02-06 13:11
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/423

**Closed by gerardroche** 2019-02-06 13:11 UTC
Labels: bug, cmdline-mode
