### ISSUE TITLE
<< (unindent) cannot be remapped

### ISSUE THREAD

**Issue by Sheepolution** [NeoVintageous/NeoVintageous#426] opened 2019-02-05 11:00 UTC
### Description
I'm trying to remap `<<` in normal mode and `<` in visual mode, but both don't seem to work.

### Steps to Reproduce
In your `.vintageousrc`, have the following remaps:
```
" Make >> and << into < >
nnoremap > >>
nnoremap > <<

" Keep VISUAL when indenting
vnoremap < <gvk
vnoremap > >gvk
```

_Note that I have to add the `k` to the visual indenting, because `gv` adds a line for some reason? That might be an issue on its own, or I might be doing something wrong._

### Expected behaviour

In normal mode:
`>` indents
`<` unindents

In visual mode:
`>` indents and stays in visual mode.
`<` unindents and stays in visual mode.

### Actual behaviour
In normal mode:
`>` indents
`<` does nothing. Only on the second lt (<<) does it unindent.

In visual mode:
`>` indents and stays in visual mode.
`<` unindents, but loses its visual mode.

### Versions

You can get Sublime Text version information from copy and pasting the output of the console `Menu > View > Show Console`.

OS: Windows 10 64 bit
Sublime Text: Version 3.1.1, Build 3176
Neovintageous: 1.8.0

Also, please include the OS and what version of the OS you're running.

### Additional Information

Console output on the first `<` in normal mode:

```
INFO:NeoVintageous.nv.cmds:key evt: <lt> repeat_count=None do_eval=True check_user_mappings=True
INFO:NeoVintageous.nv.cmds:evaluating state...
```

On the second `<` in normal mode:

```
INFO:NeoVintageous.nv.cmds:key evt: <lt> repeat_count=None do_eval=True check_user_mappings=True
INFO:NeoVintageous.nv.cmds:found missing command...
INFO:NeoVintageous.nv.cmds:found operator pending...
INFO:NeoVintageous.nv.cmds:evaluating state...
INFO:NeoVintageous.nv.vim:command: _vi_less_than_less_than {'mode': 'mode_internal_normal', 'count': 1}
```

Output of a single `>` in normal mode:

```
INFO:NeoVintageous.nv.cmds:key evt: > repeat_count=None do_eval=True check_user_mappings=True
INFO:NeoVintageous.nv.cmds:user mapping > -> >>
INFO:NeoVintageous.nv.cmds:key evt: > repeat_count=None do_eval=False check_user_mappings=False
INFO:NeoVintageous.nv.cmds:key evt: > repeat_count=None do_eval=True check_user_mappings=False
INFO:NeoVintageous.nv.cmds:evaluating state...
INFO:NeoVintageous.nv.cmds:key evt: > repeat_count=None do_eval=True check_user_mappings=False
INFO:NeoVintageous.nv.cmds:found missing command...
INFO:NeoVintageous.nv.cmds:found operator pending...
INFO:NeoVintageous.nv.cmds:evaluating state...
INFO:NeoVintageous.nv.vim:command: _vi_greater_than_greater_than {'mode': 'mode_internal_normal', 'count': 1}
```

**Comment by gerardroche** [comment] 2019-02-05 16:57
Try:

```
" Make >> and << into < > 
nnoremap > >> 
nnoremap <lt> <lt><lt> 
```

and

```
" Keep VISUAL when indenting 
vnoremap <lt> <lt>gv 
vnoremap > >gv
```

It should really work without needing to use `<lt>` too, but neo is a bit flaky when it comes to mapping angle brackets.
 

> Note that I have to add the `k` to the visual indenting, because `gv` adds a line for some reason? That might be an issue on its own, or I might be doing something wrong.

Can you explain this issue, I can't reproduce it.

**Comment by Sheepolution** [comment] 2019-02-05 19:49
Thanks! That works!

> Can you explain this issue, I can't reproduce it.

With an empty .vintageousrc, the following happens when pressing `V` -> `gv`.

![gv](https://user-images.githubusercontent.com/2232780/52300033-2df70d00-2987-11e9-9d8b-0e4250f7d597.gif)

Note how an extra line gets added after `gv`.

**Comment by gerardroche** [comment] 2019-02-06 12:38
Thanks. It tuns out **gv** is broken when in a visual mode. I'll have a fix shortly.

**Comment by gerardroche** [comment] 2019-02-06 12:43
I've opened a ticket for fixing **gc** and closing this as https://github.com/NeoVintageous/NeoVintageous/issues/247 covers the mapping angle brackets issue. It will probably require a bit of a rewrite of the underlying mapping parser to fix it.

**Closed by gerardroche** 2019-02-06 12:43 UTC

**Comment by Sheepolution** [comment] 2019-02-06 12:54
Cool, thanks.
You linked to the same ticket twice by the way. gv issue: #427

**Comment by gerardroche** [comment] 2019-02-06 12:58
Sorry, the opened tick is 427: https://github.com/NeoVintageous/NeoVintageous/issues/427

**Comment by Sheepolution** [comment] 2021-01-18 22:52
Hey, I'm back on Sublime Text, and this seems to be an issue again.
I'm not sure if NeoVintageous is based on Neovim, but I noticed Neovim has this issue as well. It's fixed in the Nightly build. See [issue 13776](https://github.com/neovim/neovim/issues/13776) in the Neovim repository.
