### ISSUE TITLE
Goto symbol within a file automatically enters visual mode

### ISSUE THREAD

**Issue by Galicarnax** [NeoVintageous/NeoVintageous#642] opened 2019-11-02 18:17 UTC
### Description
When in normal mode, if I invoke `goto symbol within a file` (which I've bound to `comma-f` via `nnoremap <leader>f :ShowOverlay overlay=goto text=@<CR>`) the symbol (e.g., function definition) becomes selected. That happens in normal ST as well (when invoked via `ctrl+r`), but when NV is enabled, this results in entering visual mode, so I always have to hit `escape` to return to normal mode. The `goto_symbol_in_project` works normally, no visual mode is entered. Also, if invoked from insert mode (where the standard `ctrl-r` shortcut works), it also does not enter visual mode.
### Steps to Reproduce
In normal mode, invoke `ShowOverlay overlay=goto text=@<CR>` with whatever key binding you happen to use for it (`comma-f` in my case).
### Expected behaviour
Jump to the selected symbold/function definition and stay in normal mode.
### Actual behaviour
Jumps to the symbol/definition and enters visual mode.

**Comment by gerardroche** [comment] 2019-11-15 08:59
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/54 (Sublime Text core issue)

> There's no way good way for neovintageous to work around it. I've opened an Sublime Text issue requesting a command option to disable the visual selection: https://github.com/SublimeTextIssues/Core/issues/3032

**Closed by gerardroche** 2019-11-15 08:59 UTC
Labels: duplicate
