### ISSUE TITLE
Implement Typewriter mode

### ISSUE THREAD

**Issue by duranivan** [NeoVintageous/NeoVintageous#624] opened 2019-08-14 12:04 UTC
### Description

I'm quite used to using a sort of typewriter mode (i.e. to maintain the window centered vertically around the cursor), for example by using the [BufferScroll](https://github.com/titoBouzout/BufferScroll) package, or [Typewriter](https://github.com/alehandrof/Typewriter). However, this kind of packages only work while in insert mode, not normal mode.

So I modified the `rc` file with the following configuration, however it makes sublime to scroll quite slowly, specially if something like the LSP package is installed:

```
nnoremap j gjzz
nnoremap k gkzz
```

In `Vim`, I can accomplish this with `set scrolloff=999`, however this option is not available in `Neovintageous`.

I would like to find a way to keep the window centered vertically around the cursor in both insert and normal modes, without compromising in performance.

Thanks in advance for any input!

### Steps to Reproduce

- Install the LSP package and use the configuration above for `j` and `k`.
- Even without LSP installed, depending on your machine, some performance issues can be noticed when scrolling (e.g. in Macbook Air 2013).

### Expected behaviour

- It should scroll smoothly without delay

### Actual behaviour

- Scrolling is quite sluggish

**Comment by gerardroche** [comment] 2019-08-15 17:47
I'm going to close this in preference of #205 (Implement `'scrolloff'`) because implementing scrolloff will be enough to do what you want.

Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/205

**Closed by gerardroche** 2019-08-15 17:47 UTC
Labels: feature
