### ISSUE TITLE
Implement changelist jumps (g; and g,)

### ISSUE THREAD

**Issue by jnns** [NeoVintageous/NeoVintageous#756] opened 2020-12-29 10:29 UTC
When I tried to use the Vim commands <kbd>g</kbd><kbd>;</kbd> and <kbd>g</kbd><kbd>,</kbd> it didn't do anything. I'm not sure if I misconfigured NeoVintageous or if they are not implemented. If that's the case, do you think it makes sense to add them?

Quote from the documentation:
 ```
CHANGE LIST JUMPS			*changelist* *change-list-jumps* *E664*

When making a change the cursor position is remembered.  One position is
remembered for every change that can be undone, unless it is close to a
previous change.  Two commands can be used to jump to positions of changes,
also those that have been undone:

							*g;* *E662*
g;               Go to [count] older position in change list.
                  If [count] is larger than the number of older change
                  positions go to the oldest change.
                  If there is no older change an error message is given.
                  (not a motion command)

							*g,* *E663*
g,               Go to [count] newer cursor position in change list.
                  Just like |g;| but in the opposite direction.
                  (not a motion command)

[…]
```

**Comment by gerardroche** [comment] 2020-12-29 13:03
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/106

**Closed by gerardroche** 2020-12-29 13:03 UTC
